# Site settings
title: McGill Biology Graduate Association
email: hello@mcgillbgsa.com
description: "Welcome to the McGill BGSA page! Here, you can find information about who we are, upcoming events, and photos of our past events as well as a compilation of handy dandy links we've found very useful over the years. "
baseurl: ""
url: "http://mcgillbgsa.github.io"

paginate: 3
paginate_path: ":num"

# Build settings
markdown: kramdown
permalink: pretty
