# Site settings
title: McGill Biology Graduate Association
email: hello@mcgillbgsa.com
description: "Welcome to the McGill BGSA page! Here, you can find information about who we are, upcoming events, and photos of our past events as well as a compilation of handy dandy links we've found very useful over the years. "
baseurl: ""
url: "http://mcgillbgsa.github.io"

paginate: 3
paginate_path: ":num"

# Build settings
markdown: kramdown
permalink: pretty

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'http://mcgillbgsa.com/'
  metadata:
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          value: "Blog Post Title"
          help: "This blog post's title"
      - name: "author"
        field:
          element: "text"
          value: "Guang Zhang, BGSA Web Admin"
          help: "Who wrote this blog post?"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          value: "update"
          placeholder: "Choose Tags"
          options: 
            - name: 'Department'
              value: 'department'
            - name: 'Update'
              value: 'update'
            - name: 'Event'
              value: 'event'
            - name: 'Information'
              value: 'information'
            - name: 'Getting Involved'
              value: 'getting-involved'
          alterable: true